#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for qstash-manager CLI project

set -e

echo "========================================"
echo "QStash Manager - Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_DIR="/Users/daniel/development/qstash-manager-project"

# Check Node.js version
check_node_version() {
    echo -e "\n${BLUE}Checking Node.js version...${NC}"

    if ! command -v node &> /dev/null; then
        echo -e "${RED}Node.js is not installed. Please install Node.js >= 18${NC}"
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        echo -e "${RED}Node.js version must be >= 18. Current: $(node -v)${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ Node.js $(node -v) OK${NC}"
}

# Check for QSTASH_TOKEN
check_qstash_token() {
    echo -e "\n${BLUE}Checking QStash token...${NC}"

    if [ -z "$QSTASH_TOKEN" ]; then
        echo -e "${YELLOW}⚠ QSTASH_TOKEN not set in environment${NC}"
        echo -e "  Get your token from: https://console.upstash.com/qstash"
        echo -e "  Set it with: export QSTASH_TOKEN=your_token"
        echo -e "  (CLI will prompt for token on first run if not set)"
    else
        echo -e "${GREEN}✓ QSTASH_TOKEN is set${NC}"
    fi
}

# Navigate to project directory
setup_project() {
    echo -e "\n${BLUE}Setting up project...${NC}"

    if [ ! -d "$PROJECT_DIR" ]; then
        echo -e "${RED}Project directory not found: $PROJECT_DIR${NC}"
        exit 1
    fi

    cd "$PROJECT_DIR"
    echo -e "${GREEN}✓ Project directory: $PROJECT_DIR${NC}"
}

# Install dependencies
install_dependencies() {
    echo -e "\n${BLUE}Installing dependencies...${NC}"

    if [ -f "package.json" ]; then
        if [ ! -d "node_modules" ]; then
            npm install
            echo -e "${GREEN}✓ Dependencies installed${NC}"
        else
            echo -e "${GREEN}✓ Dependencies already installed${NC}"
        fi
    else
        echo -e "${YELLOW}⚠ package.json not found - project setup not yet complete${NC}"
        echo -e "  Run the planner agent first to create project configuration"
    fi
}

# Build project
build_project() {
    echo -e "\n${BLUE}Building project...${NC}"

    if [ -f "package.json" ]; then
        npm run build 2>/dev/null && echo -e "${GREEN}✓ Build successful${NC}" || echo -e "${YELLOW}⚠ Build not yet configured${NC}"
    fi
}

# Run development mode
run_dev() {
    echo -e "\n${BLUE}Starting development mode...${NC}"

    if [ -f "package.json" ]; then
        echo -e "${GREEN}Starting: npm run dev${NC}"
        npm run dev
    else
        echo -e "${YELLOW}⚠ Cannot start dev mode - package.json not found${NC}"
    fi
}

# ============================================
# MAIN EXECUTION
# ============================================

check_node_version
check_qstash_token
setup_project
install_dependencies
build_project

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Development:  npm run dev"
echo "  2. Build:        npm run build"
echo "  3. Test:         npm test"
echo "  4. Local test:   npm link && qstash-manager"
echo ""
echo "Reference files:"
echo "  - DESIGN.md: Complete architecture"
echo "  - spec.md: Feature specification"
echo "  - Reference code: /Users/daniel/development/prefix/src/cli/commands/qstash-url-groups.ts"
echo ""

# Optionally start dev mode if --dev flag is passed
if [ "$1" = "--dev" ]; then
    run_dev
fi
